clearlydefined/clearlydefined

- docs/_includes/sidebar.html
- docs/_layouts/default.html
- docs/_sass/style.scss
* Change to Montserrat font.
* Remove bullets and left padding on sidebar menu items.
* Increase size of search text field and improve button style.
* Change layout of edit/history/source links, switch to ClearlyDefined color palette.
Closes issue #39.
Addresses part of issue #42.
> First batch of styling updates.

- docs/FAQ.md
> Small typo in FAQ.md

- docs/contributing-data.md
Changed but > bug in 2nd para, to try out contributing to this project.
> Fixing a typo

- docs/contributing-code.md
This Fixes #85 , and needs to be merged as soon PR [#323](https://github.com/clearlydefined/website/pull/323) will be merged, in order to let the developers know about the new environment configuration and usage.
> Issue #85 - Updated documentation reflecting environment configuration

- docs/using-data.md
- Improved exisiting "Using Data" documentation to reflect current menus and UI
- Added description around the Expanded View feature
- Fixed examples links
Closes #83
> #83 - Update Documentation to Reflect new UI

- docs/data-curation.md
Update curation principles and process as per document review from:  https://docs.google.com/document/d/13o45CNtxo_Ca234x0NvyIVHiYQu_di1dJtmqQp769mU/edit#
> Update curations principle and process doc

- docs/curation-process.md
Process for curating walkthrough document
> Creating curation process document

- docs/providers.md
https://guides.rubygems.org/name-your-gem/
> lowercase -> uppercase

- docs/curation-guidelines.md
Updating curation guidelines for NONE and NOASSERTION
> Updating curation-guidelines.md

- docs/using-data.md
Not 100% sure that the new link will work on the live site? But the old one is definitely broken.
> Fix broken link, spelling error, and stray bold

- docs/using-data.md
> exammple => example

- docs/curation-guidelines.md
> Fixing small typo

- docs/curation-guidelines.md
Encourage the review and curation of "sourcearchive" and "debsrc" definitions.
> Review and curation of "sourcearchive" and "debsrc" definitions.

- docs/index.md
Added the link to the mailing list to encourage easier access to sign up.
> Updated the index.md

- docs/contributing-code.md
This allows a contributor to quickly have a fully functional local development environment in less than 20 min (provided the already have Docker and Docker Compose installed). The linked GitHub repo has full instructions on the set up.
Signed-off-by: Nell Shamrell <nells@microsoft.com>
> points to the dockerized ClearlyDefined local environment

- docs/_includes/sidebar.html
- docs/data-curation.md
Fixes https://github.com/clearlydefined/website/issues/873
Signed-off-by: Nell Shamrell <nells@microsoft.com>
> links to contribution guidelines from a more prominent location

- docs/curation-guidelines.md
Adding space between header and table so it renders correctly
> Fixing table

- docs/_includes/sidebar.html
- docs/adding-sources.md
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
> adds documentation on sources for license information

- docs/curation-guidelines.md
Edit per the ClearlyDefined community call today
Cc: @royaljust , @capfei , @nellshamrell
> Add SPDX Matching Guidelines

- docs/adding-sources.md
Signed-off-by: Nell Shamrell <nells@microsoft.com>
> adds gitlab as a source for git components

- docs/using-data.md
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
> updates api docs

- docs/using-data.md
This should be merged after these two pull requests are deployed.
[Service Go PR](https://github.com/clearlydefined/service/pull/871)
[Crawler Go PR](https://github.com/clearlydefined/crawler/pull/444)
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
> adds docs for go components

- docs/contributing-code.md
> Fixing projects link

- docs/adding-sources.md
Task: https://github.com/clearlydefined/service/issues/882
> Add gradle plugins as a maven source

- .github/workflows/build-documentation.yaml
- package-lock.json
DRAFT: need to remove my branch and reinstate main before merging
> add action to automatically build docs when main is updated

- .gitignore
Add folder .docusaurus to the .gitignore file
> docs: add .docusaurus to .gitignore

- blog/2024-05-16-unveiling-clearlydefined.md
Add blog post Unveiling ClearlyDefined
> docs: add blog unveiling clearlydefined

- docs/resources/faq.md
Remove NPM1k as per PR #154, now for the new documentation website.
> docs: remove NPM1k as per PR #154

- docs/get-involved/using-data.md
Provide notes about current limitations as per PR #158, now for the new documentation website.
> docs: provide notes about limitations as per pr #158

- docusaurus.config.js
- package-lock.json
- package.json
Add redirect plugin (plugin-client-redirects) and a list of a few redirects
> docs: add redirect plugin and list of redirects

- docs/resources/coordinates.md
Adding more information about coordinates and mapping with purl types. Thanks to @qtomlinson for researching this and providing a comprehensive overview with examples.
> docs: add coordinates

- docs/get-involved/adding-sources.md
Update harvest information based on:
https://github.com/clearlydefined/service/edit/master/docs/determining-declared-license.md
Thanks @qtomlinson for the tip!
> docs: update harvest information

- blog/2024-07-23-conda.md
- blog/2024-08-06-guac.md
Update blog to include posts about conda and guac support.
> docs: update blog about conda and guac

- docs/resources/roadmap.md
> docs: update roadmap 2024

- blog/2024-08-20-sap.md
> docs: add sap case study

- package-lock.json
- package.json
update to latest docusaurus version 3.5.2
> docs: update to docusaurus 3.5.2

- docusaurus.config.js
Add links to UI and API on the top menu and footer.
> docs: add links to UI and API

- blog/2024-10-16-elections.md
Add blog announcing election results for the steering and outreach committees
> docs: add election results

- docs/community/events.md
Update 2 upcoming events:
- SOSS Fusion
- Open Compliance Summit
> docs: update 2 upcoming events

- docs/community/members.md
Add elected Steering and Outreach committees.
> docs: add elected committees

- docs/community/members.md
> docs: update members

- blog/2024-11-13-version2.md
Add blog post announcing ClearlyDefined version 2.0 from @elrayle
> docs: add blog post announcing v.2

- docs/community/events.md
Add FOSDEM presentation from Qing and Jeff
> docs: add fosdem

- docs/curation/curation-api.md
- docs/curation/curation-guidelines.md
- docs/curation/curation-process.md
- docs/curation/data-donation.md
Add Curation via API guide from @yashkohli88. Closes #223
> docs: add curation via api guide

- docs/curation/curation-api.md
Formatting of the json payload in curl command has been fixed in curation-api.md file.
> Fixed formatting of json payload in curl command

- blog/2024-11-06-soss-fusion.md
- blog/2024-12-11-recap-2024.md
Sync blog by adding posts with Recap of 2024 and presentation at SOSS Fusion
> docs: sync blog

- docs/curation/curation-api.md
Refer to Candice's comment: https://discord.com/channels/414106994996281365/419968097391345664/1339011245755600990
> Update JSON payload for the curation API

- docs/community/meetings.md
Updating Community meeting time to 10:30am Eastern.
> docs: update community meeting time
